# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35fe1e6ca7995e0cb64e8dc6def070b32f9d98f60875379a8782e377632bbeeb3ac282be3dfb8afdd323582b73b1c84148581242af607f3f9db30f02cae36a55

test:
  secret_key_base: 230730bf62dcac1382958e62d7a0d5498d5b4a19b5e0bc56b042a291d36061d941462ff10244970533dd6f4d30840392c0fdb1db9e165537328c027430ed3dc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
