# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5440749d149949620189bfbb966d3f51313e312fdb4029be007cbf446783b7a81547da68d618d2b92461e801c068e9dc5aafe7a990be1228fb4637fcec108fb2

test:
  secret_key_base: c1e34b14aed6c58bfbd620eb1b032386ad4091b3d00ce1311bfa03a6243af4108930589ef50bf2a30a094c3a4032236486687e84a0e5a6a01364e2a8fc838173

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
